title: Sample Content from Newfangled
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.75
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#ffffff'
    - '#bec5be'
    - '#e01d34'
    - '#2a335b'
    - '#f19ca6'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: does-it-work
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.31323
layout_spectrum: 0
