name: does-it-work
favicon: null
layout_spectrum: 0.49449
typography_spectrum: 0.31323
title: Sample Content from Newfangled
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bec5be'
    - '#e01d34'
    - '#2a335b'
    - '#f19ca6'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
